// ✅ Flip.ai REAL SERVER.JS — Upload → OpenAI DALL·E → Return Enhanced URL

import express from 'express';
import multer from 'multer';
import cors from 'cors';
import path from 'path';
import { fileURLToPath } from 'url';
import fs from 'fs';
import OpenAI from 'openai';

// ✅ Fix __dirname for ES Modules
const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

// ✅ Load OpenAI key from environment
const openai = new OpenAI({
  apiKey: process.env.OPENAI_API_KEY,
});

const app = express();
const port = process.env.PORT || 10000;

// ✅ Allow only your Netlify frontend
const allowedOrigins = ['https://flip-ai.netlify.app'];
app.use(
  cors({
    origin: (origin, callback) => {
      if (!origin || allowedOrigins.includes(origin)) {
        callback(null, true);
      } else {
        callback(new Error('CORS policy: Not allowed by CORS'));
      }
    },
    credentials: true,
  })
);

app.use(express.json());

// ✅ Store uploads locally
const storage = multer.diskStorage({
  destination: (req, file, cb) => cb(null, './uploads'),
  filename: (req, file, cb) => cb(null, `${Date.now()}-${file.originalname}`),
});
const upload = multer({ storage });

// ✅ Serve uploads for public access
app.use('/uploads', express.static(path.join(__dirname, 'uploads')));

// ✅ POST /api/enhance — Upload → DALL·E → Return Enhanced URL
app.post('/api/enhance', upload.single('propertyImage'), async (req, res) => {
  console.log('✅ Image received:', req.file?.originalname);

  if (!req.file) {
    return res.status(400).json({ error: 'No image uploaded.' });
  }

  const budget = req.body.budget || 0;

  const localImagePath = path.join(__dirname, 'uploads', req.file.filename);

  try {
    // ✅ Call OpenAI DALL·E Variations API
    const response = await openai.images.createVariation({
      image: fs.createReadStream(localImagePath),
      n: 1,
      size: '1024x1024',
    });

    const enhancedImageUrl = response.data[0].url;

    console.log('✅ OpenAI Enhanced Image:', enhancedImageUrl);

    res.json({
      uploadedImageUrl: `${req.protocol}://${req.get('host')}/uploads/${req.file.filename}`,
      enhancedImageUrl,
      budget: Number(budget),
      description: 'Real AI-enhanced variation generated by OpenAI DALL·E',
    });

  } catch (error) {
    console.error('❌ OpenAI API Error:', error);
    res.status(500).json({ error: 'Failed to enhance image with OpenAI.' });
  }
});

// ✅ Health check
app.get('/', (req, res) => {
  res.send('✅ Flip.ai backend is LIVE — real upload + OpenAI DALL·E enhancement.');
});

app.listen(port, () => {
  console.log(`✅ Flip.ai backend running on port ${port}`);
});
