// ============================================================
// ✅ Flip.ai Backend — Image Enhance Only, Tier 1, Fresh Start
// ============================================================

import express from 'express';
import multer from 'multer';
import fs from 'fs';
import cors from 'cors';
import dotenv from 'dotenv';
import OpenAI from 'openai';

dotenv.config();

const openai = new OpenAI({
  apiKey: process.env.OPENAI_API_KEY,
});

const app = express();
app.use(express.json());

app.use(cors({
  origin: [
    'http://localhost:3000',
    'https://flip-ai.netlify.app',
    'https://www.flip-ai.netlify.app'
  ],
}));

// ✅ Upload setup
const uploadDir = '/tmp/uploads';
if (!fs.existsSync(uploadDir)) {
  fs.mkdirSync(uploadDir, { recursive: true });
  console.log('✅ Created upload directory:', uploadDir);
}

const storage = multer.diskStorage({
  destination: (req, file, cb) => cb(null, uploadDir),
  filename: (req, file, cb) => cb(null, Date.now() + '-' + file.originalname)
});
const upload = multer({ storage });

// ✅ Health check
app.get('/', (req, res) => {
  res.send('✅ Flip.ai backend is alive.');
});

// ============================================================
// ✅ /api/enhance — Tier 1 Basic Enhancement
// ============================================================
app.post('/api/enhance', upload.single('image'), async (req, res) => {
  console.log("🖼️ Received image for enhancement");

  if (!req.file) {
    return res.status(400).json({ error: "Image is required" });
  }

  const investment = parseFloat(req.body.investment || 0);
  console.log("✅ Investment:", investment);

  let tier = "Tier 1 — Basic";
  let stylePrompt = `
Photo of a light blue house with boarded-up windows.
Replace only the boarded-up windows with clear glass windows matching the house’s style.
Keep everything else the same: paint, yard, door, trees.
Preserve a realistic, before-and-after look.
  `.trim();

  console.log(`✨ Using Tier: ${tier}`);

  try {
    const dalleResponse = await openai.images.generate({
      model: "dall-e-3",
      prompt: stylePrompt,
      n: 1,
      size: "1024x1024"
    });

    const enhancedImageUrl = dalleResponse.data[0].url;
    console.log("✅ DALL·E returned:", enhancedImageUrl);

    res.json({
      enhancedImageUrl,
      tierUsed: tier,
      description: "Generated by Flip.ai — Tier 1 Enhancement."
    });

  } catch (err) {
    console.error("❌ /api/enhance error:", err);
    res.status(500).json({
      error: "Image enhancement failed",
      details: err.message
    });
  } finally {
    fs.unlink(req.file.path, () => {});
  }
});

// ✅ Start server
const PORT = process.env.PORT || 8080;
app.listen(PORT, () => {
  console.log(`🚀 Flip.ai backend running on port ${PORT}`);
});
